version: '3.7'

services:
  product:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file: ./.env
    networks:
      backend:

networks:
  backend:
    ipam:
      driver: default
